### ISSUE TITLE
DEPRECATION: object proxying in ember 1.11.0  will 

### ISSUE THREAD

**Issue by msalahz** [chrisfarber/ember-breadcrumbs#22]
I'm using using ember beta and I'm getting the following error for routes doesn't have breadCrumb property in it's controllers :

"DEPRECATION: You attempted to access breadCrumb from (generated home.error controller), but object proxying is deprecated. Please use model.breadCrumb instead.

**Comment by chrisfarber** [comment]
This warning should be harmless (except for the annoyance). Eventually, once object proxying is removed, this warning would go away.

If you have any ideas for how to suppress these warnings, let me know or submit a PR.

**Comment by msalahz** [comment]
@chrisfarber , I really don't know how will handle that, I thought about find a way to now if the controller is  auto-generated by ember or not but this will not handle all cases. 
so I'm thinking now to force something like provide a mixin for addon users and any one want to support breadcrumbs in their controllers should implement that mixin and the code will go through all controller implement the mixin not all project controllers, I hope I made myself clear ?  What you think ?

**Comment by msalahz** [comment]
@chrisfarber what about this [example](http://blog.salsify.com/engineering/automatic-breadcrumbs-in-ember.js) ? Which exclude any route from the trail by not defining a breadcrumbName

**Comment by chrisfarber** [comment]
This is how ember-breadcrumbs works, and it has worked that way since before that blog post was published.

As I said, this deprecation warning is spurious. Ember-breadcrumbs is not making use of the behavior that is being deprecated.

If you want to make this warning go away, you have some options:
- Define an Ember.Controller for the affected routes. Ember.ObjectController (which is autogenerated for you) is, itself, also deprecated.
- Define the property "breadCrumb" as `null` or `undefined` on your afflicted controllers.
- Find a way to silence this warning and submit a pull request

**Comment by msalahz** [comment]
Cool, Thanks @WooDzu .

**Comment by chrisfarber** [comment]
Unfortunately that fix introduced its own problems, see #27. I've reverted the attempted workaround.

**Comment by msalahz** [comment]
:(

**Comment by msalahz** [comment]
Any updates about this one ?

**Comment by chrisfarber** [comment]
Try using this: https://github.com/cibernox/ember-disable-proxy-controllers

If you aren't using object-proxying controllers, you won't get this deprecation warning.

**Comment by msalahz** [comment]
Works, Thanks!
